password = "secure"
OPENAI_API_KEY = "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"