password = "secure"
OPENAI_API_KEY = "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"